# -*- coding: utf-8 -*-
"""machine_learning_complete.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I_3qGHkhJla2-tEuWATVZ0ILQJALkSwx
"""

import numpy as np
import pandas as pd

dataset = pd.read_csv("/content/loan.csv")
dataset.head(3)

dataset.shape

dataset.isnull().sum()

